version: '3.8'

services:
  backend:
    container_name: django_app
    build:
      context: ./backend/config
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env

  frontend:
    container_name: react_app
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev

networks:
  default:
    driver: bridge