version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    # МЕНЯЕМ КОМАНДУ: добавляем backend/
    command: python backend/config/manage.py runserver 0.0.0.0:8000
    volumes:
      # МЕНЯЕМ ПУТЬ: монтируем всю папку проекта в /app
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env

networks:
  default:
    driver: bridge