# Generated by Django 5.1.7 on 2025-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_pass',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_stats',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Статистика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_voite',
            field=models.BooleanField(default=False, help_text='Может ли он голосовать?', verbose_name='Голос'),
        ),
    ]
